version: '3.1'
services:
  db:
    image: postgres:13.1-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    expose:
      - ${DB_PORT_INTERN}
    ports:
      - ${DB_PORT_INTERN}:${DB_PORT}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    hostname: ${HOST_REDIS}
    ports:
      - ${PORT_REDIS}:${PORT_REDIS}

volumes:
  pgdata:
